package org.apache.solr.ide.configset.schema.documentation

import org.apache.solr.ide.model.schema.SolrAnalyzerChain
import org.apache.solr.ide.model.schema.SolrAnalyzerComponent
import org.apache.solr.ide.model.vocabulary.SolrClassAttribute
import org.apache.solr.ide.model.vocabulary.SolrClassEntry
import org.apache.solr.ide.model.vocabulary.SolrClassKind
import org.apache.solr.ide.model.schema.SolrField
import org.apache.solr.ide.model.schema.SolrFieldProperties
import org.apache.solr.ide.model.schema.SolrFieldType
import org.apache.solr.ide.model.schema.SolrSchemaVersion
import org.apache.solr.ide.model.schema.SolrValueType
import org.apache.solr.ide.model.SolrVersionSelection
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * The text shown to the user, tested without an editor.
 *
 * The hint and the documentation popup render through the same code precisely so they cannot
 * disagree about what a field matches, so both are covered here.
 */
class SolrFieldPresentationTest {

    /** What a configset generated by a current Solr declares, so the defaults are today's. */
    private val modernSchema = SolrSchemaVersion.of("1.7")

    private val stringType = SolrFieldType("string", "solr.StrField")

    private val textType = SolrFieldType(
        name = "text_general",
        className = "solr.TextField",
        indexAnalyzer = SolrAnalyzerChain(
            tokenizer = SolrAnalyzerComponent("solr.StandardTokenizerFactory"),
            filters = listOf(SolrAnalyzerComponent("solr.LowerCaseFilterFactory")),
        ),
    )

    private val prefixType = textType.copy(
        name = "text_prefix",
        indexAnalyzer = textType.indexAnalyzer!!.copy(
            filters = textType.indexAnalyzer!!.filters + SolrAnalyzerComponent("solr.EdgeNGramFilterFactory"),
        ),
    )

    private val unknownType = SolrFieldType(
        name = "custom",
        className = "solr.TextField",
        indexAnalyzer = SolrAnalyzerChain(tokenizer = SolrAnalyzerComponent("com.example.MysteryTokenizerFactory")),
    )

    private val strFieldEntry = SolrClassEntry(
        SolrClassKind.FIELD_TYPE,
        "org.apache.solr.schema.StrField",
        "solr.StrField",
        listOf(SolrClassAttribute("docValuesFormat")),
    )

    private val edgeNGramEntry = SolrClassEntry(
        SolrClassKind.TOKEN_FILTER,
        "org.apache.lucene.analysis.ngram.EdgeNGramFilterFactory",
        "solr.EdgeNGramFilterFactory",
        listOf(
            SolrClassAttribute("maxGramSize", SolrValueType.INTEGER, required = true),
            SolrClassAttribute("minGramSize", SolrValueType.INTEGER, required = true),
            SolrClassAttribute("preserveOriginal", SolrValueType.BOOLEAN, defaultValue = "false"),
            SolrClassAttribute("luceneMatchVersion", SolrValueType.FREE),
        ),
    )

    private fun field(type: String) = SolrField("f", type)

    // --- the documentation popup ----------------------------------------------------------------

    @Test
    fun `field documentation names the field, its type and what it matches`() {
        val html = SolrFieldPresentation.fieldDocumentation(
            SolrField("sku", "string", attributes = mapOf("indexed" to "true")),
            stringType,
            SolrVersionSelection.DEFAULT,
            modernSchema,
        )
        assertTrue(html.contains("sku"))
        assertTrue(html.contains("string"))
        assertTrue(html.contains("whole value, case-sensitive"))
    }

    /**
     * The caveat that keeps the claim defensible. A reader who knows wildcards work on any indexed
     * field will assume the hint is wrong unless it says what it means.
     */
    @Test
    fun `documentation states that the claim is about efficient matching`() {
        val html = SolrFieldPresentation.fieldDocumentation(field("string"), stringType, SolrVersionSelection.DEFAULT, modernSchema)
        assertTrue(html.contains("wid*"))
        assertTrue(html.contains("efficiently") || html.contains("<i>efficiently</i>"))
    }

    /** The three-level resolution is the part no external documentation can supply. */
    @Test
    fun `field documentation shows each property's value and where it came from`() {
        val html = SolrFieldPresentation.fieldDocumentation(
            SolrField("sku", "string", attributes = mapOf("stored" to "false")),
            stringType.copy(attributes = mapOf("sortMissingLast" to "true")),
            SolrVersionSelection.DEFAULT,
            modernSchema,
        )
        assertTrue("declared on the field", html.contains("on this field"))
        assertTrue("inherited from the type", html.contains("from the field type"))
        assertTrue("fallen back to Solr", html.contains("Solr default"))
        assertTrue("undetermined defaults are admitted", html.contains("depends on the field type"))
    }

    @Test
    fun `field type documentation shows both chains in pipeline order`() {
        val html = SolrFieldPresentation.fieldTypeDocumentation(prefixType, SolrVersionSelection.DEFAULT)
        assertTrue(html.contains("StandardTokenizerFactory"))
        assertTrue(html.contains("EdgeNGramFilterFactory"))
        assertTrue(html.contains("Index analyser"))
    }

    @Test
    fun `documentation declines to claim a match behaviour it could not determine`() {
        val html = SolrFieldPresentation.fieldTypeDocumentation(unknownType, SolrVersionSelection.DEFAULT)
        assertTrue(html.contains("not determined"))
    }

    @Test
    fun `documentation links to the guide and names which version it linked to`() {
        val html = SolrFieldPresentation.fieldDocumentation(field("string"), stringType, SolrVersionSelection.DEFAULT, modernSchema)
        assertTrue(html.contains("https://solr.apache.org/guide/solr/latest/"))
        assertTrue(html.contains("latest release"))
    }

    /**
     * The version named in the popup is the one the value came from, not the text in the file.
     *
     * A schema declaring nothing is running under Solr's `1.0` rules, so naming anything else —
     * or nothing — would attribute the value to a version that did not produce it.
     */
    @Test
    fun `a schema declaring no version documents the version Solr assumes for it`() {
        val html = SolrFieldPresentation.fieldDocumentation(
            field("string"),
            stringType,
            SolrVersionSelection.DEFAULT,
            SolrSchemaVersion.of(null),
        )
        assertTrue("expected the assumed version named: $html", html.contains("schema version 1.0"))
    }

    /** A half-typed attribute is the normal state of a file being edited, and resolves the same way. */
    @Test
    fun `an unparseable version documents the assumed one`() {
        val html = SolrFieldPresentation.fieldDocumentation(
            field("string"),
            stringType,
            SolrVersionSelection.DEFAULT,
            SolrSchemaVersion.of("not-a-version"),
        )
        assertTrue("expected the assumed version named: $html", html.contains("schema version 1.0"))
    }

    @Test
    fun `an undeclared type is reported rather than rendered as blank`() {
        val html = SolrFieldPresentation.fieldDocumentation(field("nope"), null, SolrVersionSelection.DEFAULT, modernSchema)
        assertTrue(html.contains("not declared"))
    }

    /** Field names come from a file the user controls, so they must not be able to inject markup. */
    @Test
    fun `text from the configset is escaped`() {
        val html = SolrFieldPresentation.fieldDocumentation(
            SolrField("<script>alert(1)</script>", "string"),
            stringType,
            SolrVersionSelection.DEFAULT,
            modernSchema,
        )
        assertTrue("raw markup must not survive", !html.contains("<script>"))
        assertTrue(html.contains("&lt;script&gt;"))
    }

    // --- the class documentation popup -------------------------------------------------------

    @Test
    fun `a class popup names the kind and both spellings`() {
        val html = SolrFieldPresentation.classDocumentation(strFieldEntry, null, SolrVersionSelection.DEFAULT)
        assertTrue(html.contains("solr.StrField"))
        assertTrue("the kind belongs in the definition: $html", html.contains("field type class"))
        assertTrue(html.contains("org.apache.solr.schema.StrField"))
    }

    @Test
    fun `a class popup lists the attributes the class accepts with their value types`() {
        val html = SolrFieldPresentation.classDocumentation(edgeNGramEntry, null, SolrVersionSelection.DEFAULT)
        assertTrue(html.contains("maxGramSize"))
        assertTrue("an int attribute reads as a whole number: $html", html.contains("whole number"))
        assertTrue("a bool attribute reads as true or false: $html", html.contains("true or false"))
    }

    @Test
    fun `a class with no known attributes claims nothing about them`() {
        val bare = SolrClassEntry(SolrClassKind.TOKENIZER, "org.example.T", "solr.T")
        val html = SolrFieldPresentation.classDocumentation(bare, null, SolrVersionSelection.DEFAULT)
        assertFalse("no attribute table for an empty list: $html", html.contains("Accepts"))
    }

    @Test
    fun `a factory popup links the guide page for its kind`() {
        val html = SolrFieldPresentation.classDocumentation(edgeNGramEntry, null, SolrVersionSelection.DEFAULT)
        assertTrue("expected the filters page: $html", html.contains("/indexing-guide/filters.html"))
    }

    @Test
    fun `a field type class popup links the field types page`() {
        val html = SolrFieldPresentation.classDocumentation(strFieldEntry, null, SolrVersionSelection.DEFAULT)
        assertTrue("expected the field types page: $html", html.contains("/indexing-guide/field-types-included-with-solr.html"))
    }

    @Test
    fun `specifics render under the configset heading`() {
        val html = SolrFieldPresentation.classDocumentation(
            strFieldEntry,
            "Used by 1 field type: <code>string</code>.",
            SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("In this configset:"))
        assertTrue(html.contains("<code>string</code>"))
    }

    /** The one-sentence Javadoc summary, when the catalog carries one. */
    @Test
    fun `a class popup shows its documentation summary when the catalog carries one`() {
        val html = SolrFieldPresentation.classDocumentation(
            edgeNGramEntry.copy(summary = "Creates new instances of EdgeNGramTokenFilter."),
            null,
            SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("Creates new instances of EdgeNGramTokenFilter."))
    }

    /** No `-sources` documentation for this class is no paragraph, not an empty one. */
    @Test
    fun `a class with no summary shows no documentation paragraph`() {
        val html = SolrFieldPresentation.classDocumentation(strFieldEntry, null, SolrVersionSelection.DEFAULT)
        assertTrue("strFieldEntry carries no summary", strFieldEntry.summary == null)
        assertFalse("no empty <p></p> for a missing summary", html.contains("<p></p>"))
    }

    // --- the factory-tag complete-configuration popup ----------------------------------------

    /**
     * The configuration table is the point of documenting the tag: every attribute the class
     * accepts, each at its effective value, written or defaulted.
     */
    @Test
    fun `a factory tag popup shows every attribute at its effective value`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "filter",
            edgeNGramEntry,
            mapOf("minGramSize" to "2", "maxGramSize" to "15"),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("<b>Configuration</b>"))
        assertTrue(html.contains("minGramSize"))
        assertTrue(html.contains("maxGramSize"))
        assertTrue(html.contains("preserveOriginal"))
        assertTrue(html.contains("luceneMatchVersion"))
        assertTrue("written minGramSize must appear", html.contains("<b>2</b>"))
        assertTrue("the catalog default must appear for the unwritten attribute", html.contains("false"))
        assertTrue("defaults are labelled as Solr's: $html", html.contains("Solr default"))
        assertTrue("written values name the filter: $html", html.contains("on this filter"))
    }

    /** Written and defaulted rows must be visually distinguishable, not merely both present. */
    @Test
    fun `written factory attributes are bold and defaults are not`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "filter",
            edgeNGramEntry,
            mapOf("minGramSize" to "2"),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue("a written value is bold: $html", html.contains("<td><b>2</b></td>"))
        assertTrue(
            "a default is plain text, not bold: $html",
            html.contains("<td>false</td>") && !html.contains("<td><b>false</b></td>"),
        )
    }

    /** A required attribute the tag omits still appears — dropping it would understate the class. */
    @Test
    fun `a missing required factory attribute is marked rather than invented`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "filter",
            edgeNGramEntry,
            emptyMap(),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue("required, not set must appear: $html", html.contains("required, not set"))
        assertTrue("no invented number for minGramSize: $html", html.contains("—"))
        assertFalse("must not claim a Solr default for a required attribute", html.contains("minGramSize</code></td><td>false"))
    }

    /** An optional attribute with no recorded default is not silently dropped either. */
    @Test
    fun `an unset optional factory attribute appears without a fabricated value`() {
        val resolved = SolrFieldPresentation.effectiveFactoryAttributes(
            edgeNGramEntry,
            emptyMap(),
        ).associateBy { it.attribute.name }
        assertEquals(SolrFactoryAttributeOrigin.UNSET, resolved.getValue("luceneMatchVersion").origin)
        assertNull(resolved.getValue("luceneMatchVersion").value)
        assertEquals(SolrFactoryAttributeOrigin.SOLR_DEFAULT, resolved.getValue("preserveOriginal").origin)
        assertEquals("false", resolved.getValue("preserveOriginal").value)
    }

    /** Written attributes sort ahead of defaults, matching the field property table. */
    @Test
    fun `written factory attributes sort before defaults`() {
        val resolved = SolrFieldPresentation.effectiveFactoryAttributes(
            edgeNGramEntry,
            mapOf("preserveOriginal" to "true"),
        )
        assertEquals("preserveOriginal", resolved.first().attribute.name)
        assertEquals(SolrFactoryAttributeOrigin.TAG, resolved.first().origin)
    }

    /** A class with no known attributes claims nothing about configuration. */
    @Test
    fun `a factory with no known attributes claims no configuration table`() {
        val bare = SolrClassEntry(SolrClassKind.TOKENIZER, "org.example.T", "solr.T")
        val html =
            SolrFieldPresentation.factoryDocumentation("tokenizer", bare, emptyMap(), SolrVersionSelection.DEFAULT)
        assertFalse("no configuration table for an empty list: $html", html.contains("Configuration"))
    }

    @Test
    fun `a factory tag popup names the kind and the tag`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "filter",
            edgeNGramEntry,
            emptyMap(),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("&lt;filter&gt;"))
        assertTrue(html.contains("token filter factory"))
        assertTrue(html.contains("solr.EdgeNGramFilterFactory"))
    }

    /**
     * The tag comes from the file and the kind from the catalog, so a class written on the wrong
     * element is described as what it is *where it is*.
     *
     * A token filter factory on a `<tokenizer>` is a configuration Solr rejects, and one a reader is
     * plausibly hovering *because* it does not work. Deriving the element from the entry's kind
     * would print `<filter>` over a tag that says `tokenizer` and label the written value "on this
     * filter", sending them to edit an element the file does not contain — the popup silently
     * repairing the file instead of describing it. The kind stays the catalog's, because that is the
     * half that is true: naming both is what makes the mismatch legible.
     */
    @Test
    fun `a factory popup names the tag the file wrote, not the one the class belongs on`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "tokenizer",
            edgeNGramEntry,
            mapOf("minGramSize" to "2"),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue("the element written in the file: $html", html.contains("&lt;tokenizer&gt;"))
        assertFalse("must not invent the element the class belongs on: $html", html.contains("&lt;filter&gt;"))
        assertTrue("the origin follows the tag: $html", html.contains("on this tokenizer"))
        assertFalse("the origin must not follow the kind: $html", html.contains("on this filter"))
        assertTrue("the class is still what the catalog says it is: $html", html.contains("token filter factory"))
    }

    /** `charFilter` is one word written and two spoken, and the label is prose. */
    @Test
    fun `a char filter tag is named in words rather than echoed`() {
        val html = SolrFieldPresentation.factoryDocumentation(
            "charFilter",
            edgeNGramEntry,
            mapOf("minGramSize" to "2"),
            SolrVersionSelection.DEFAULT,
        )
        assertTrue("expected the spoken form: $html", html.contains("on this char filter"))
        assertTrue("the element keeps the file's spelling: $html", html.contains("&lt;charFilter&gt;"))
    }

    // --- the factory-attribute documentation popup -----------------------------------------------

    @Test
    fun `a required factory attribute names its owner type and required marker`() {
        val attribute = edgeNGramEntry.attribute("minGramSize")!!
        val html = SolrFieldPresentation.classAttributeDocumentation(
            edgeNGramEntry, attribute, SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("minGramSize"))
        assertTrue(html.contains("solr.EdgeNGramFilterFactory"))
        assertTrue("expected the value type: $html", html.contains("whole number"))
        assertTrue("expected the required marker: $html", html.contains("Required"))
        assertFalse("a required attribute has no default row: $html", html.contains("Default"))
    }

    @Test
    fun `a defaulted factory attribute shows its catalog default`() {
        val attribute = edgeNGramEntry.attribute("preserveOriginal")!!
        val html = SolrFieldPresentation.classAttributeDocumentation(
            edgeNGramEntry, attribute, SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("true or false"))
        assertTrue(html.contains("Default") && html.contains("false"))
        assertFalse(html.contains("Required"))
    }

    /**
     * FREE means the generator could not narrow the type. Promising "any value" would overclaim,
     * so the Accepts row is simply absent — the same empty rendering the class-level table uses.
     */
    @Test
    fun `a free-typed factory attribute omits the accepts row`() {
        val attribute = edgeNGramEntry.attribute("luceneMatchVersion")!!
        val html = SolrFieldPresentation.classAttributeDocumentation(
            edgeNGramEntry, attribute, SolrVersionSelection.DEFAULT,
        )
        assertTrue(html.contains("Read by"))
        assertFalse("FREE must not invent an accepts line: $html", html.contains("Accepts"))
    }

    @Test
    fun `a factory attribute popup links the guide page for its class kind`() {
        val attribute = edgeNGramEntry.attribute("minGramSize")!!
        val html = SolrFieldPresentation.classAttributeDocumentation(
            edgeNGramEntry, attribute, SolrVersionSelection.DEFAULT,
        )
        assertTrue("expected the filters page: $html", html.contains("/indexing-guide/filters.html"))
    }

    // --- the meaning of a property's resolved value ----------------------------------------------

    @Test
    fun `the property table states the consequence of the value that is in effect`() {
        val field = SolrField("sku", "string", attributes = mapOf("stored" to "false"))
        val html = SolrFieldPresentation.fieldDocumentation(
            field, stringType, SolrVersionSelection.DEFAULT, modernSchema,
        )
        assertTrue(
            "the false consequence must be stated",
            "No original value is kept for retrieval" in html,
        )
        assertFalse(
            "the true consequence must not appear for a false value",
            "The original value is returned in results" in html,
        )
    }

    @Test
    fun `the opposite value gets the opposite sentence`() {
        val field = SolrField("sku", "string", attributes = mapOf("stored" to "true"))
        val html = SolrFieldPresentation.fieldDocumentation(
            field, stringType, SolrVersionSelection.DEFAULT, modernSchema,
        )
        assertTrue("The original value is returned in results" in html)
    }

    /**
     * `stored="false"` bounds one retrieval route, not all of them. A field carrying doc values can
     * still come back — through `useDocValuesAsStored` on a wildcard `fl`, or by being named
     * explicitly — and the demo's own schema declares a version where that flag defaults on. A popup
     * saying the value can never be displayed would be confidently wrong about the common case.
     */
    @Test
    fun `a non-stored field with doc values is never called undisplayable`() {
        val field = SolrField(
            "sku", "string",
            attributes = mapOf("stored" to "false", "docValues" to "true"),
        )
        val html = SolrFieldPresentation.fieldDocumentation(
            field, stringType, SolrVersionSelection.DEFAULT, modernSchema,
        )
        assertTrue(
            "the stored switch still states its own consequence",
            "No original value is kept for retrieval" in html,
        )
        assertTrue(
            "and it must leave the doc-values route open",
            "can still put a value in results" in html,
        )
        assertFalse(
            "nothing may claim the value is simply not displayable",
            "but not displayed" in html,
        )
    }

    /**
     * `useDocValuesAsStored="false"` drops the field from a wildcard `fl`; it does not make the doc
     * values unreachable, because naming the field explicitly still returns them.
     */
    @Test
    fun `useDocValuesAsStored false bounds the wildcard rather than every request`() {
        val field = SolrField(
            "sku", "string",
            attributes = mapOf("docValues" to "true", "useDocValuesAsStored" to "false"),
        )
        val html = SolrFieldPresentation.fieldDocumentation(
            field, stringType, SolrVersionSelection.DEFAULT, modernSchema,
        )
        assertTrue(
            "an explicit request must still be described as returning the value",
            "naming it explicitly still returns its doc values" in html,
        )
        assertFalse(
            "no blanket claim that doc values never come back",
            "Doc values are not returned" in html,
        )
    }

    /**
     * Setting `sortMissingLast` resolves `sortMissingFirst` to `false`, and a sentence claiming
     * missing values sort lowest would describe an order the sibling flag has just overridden. Each
     * false sentence says only what its own flag does not do, so the two cannot contradict.
     */
    @Test
    fun `a false sortMissing flag claims no effective ordering`() {
        val field = SolrField("sku", "string", attributes = mapOf("sortMissingLast" to "true"))
        val html = SolrFieldPresentation.fieldDocumentation(
            field, stringType, SolrVersionSelection.DEFAULT, modernSchema,
        )
        assertTrue(
            "the flag that is set states its effect",
            "sort after all others" in html,
        )
        assertFalse(
            "the flag that is not set must not contradict it",
            "sort as though the value were lowest" in html,
        )
    }

    /**
     * An undetermined value has no consequence to state, and picking one of the two would be exactly
     * the confident wrong answer the null value exists to avoid. The neutral summary is the fallback.
     */
    @Test
    fun `an undetermined value falls back to the value-neutral summary`() {
        val unknownType = SolrFieldType("mystery", "com.example.MysteryFieldType")
        val field = SolrField("odd", "mystery")
        val html = SolrFieldPresentation.fieldDocumentation(
            field, unknownType, SolrVersionSelection.DEFAULT, modernSchema, typeTraits = null,
        )
        assertTrue(
            "the neutral summary must stand in",
            "Whether a column-oriented structure is built" in html,
        )
        assertFalse("no column store claim either way", "A column store is built" in html)
        assertFalse("no column store claim either way", "No column store;" in html)
    }

    @Test
    fun `hovering a property attribute states the consequence under its resolved value`() {
        val field = SolrField("sku", "string", attributes = mapOf("stored" to "false"))
        val property = SolrFieldProperties.byName("stored")!!
        val html = SolrFieldPresentation.propertyDocumentation(
            property = property,
            effective = SolrFieldProperties.resolve(property, field, stringType, modernSchema),
            version = SolrVersionSelection.DEFAULT,
            schemaVersion = modernSchema,
        )
        assertTrue("No original value is kept for retrieval" in html)
    }

    /**
     * On a fieldType there is no field to resolve against, so there is no value and no consequence.
     * The general half — summary, accepted values, Solr's default — is all a type can be told.
     */
    @Test
    fun `hovering a property on a field type states no consequence`() {
        val html = SolrFieldPresentation.propertyDocumentation(
            property = SolrFieldProperties.byName("stored")!!,
            effective = null,
            version = SolrVersionSelection.DEFAULT,
            schemaVersion = modernSchema,
        )
        assertFalse("The original value is" in html)
    }
    /**
     * The chain links to the guide under either spelling.
     *
     * `analyzerComponentPage` decides which guide page a component belongs on by the suffix of its
     * class name, so a component spelled `name="lowercase"` matched none of them and rendered as
     * bare text. That left one popup disagreeing with itself: the match line above the chain reads
     * the same components and resolves them correctly, so the chain was the only part that looked
     * unrecognized — on precisely the configsets Solr ships.
     */
    @Test
    fun `an SPI-spelled chain links to the guide like a class-spelled one`() {
        val spiType = SolrFieldType(
            name = "text_general",
            className = "solr.TextField",
            indexAnalyzer = SolrAnalyzerChain(
                tokenizer = SolrAnalyzerComponent("standard"),
                filters = listOf(SolrAnalyzerComponent("lowercase")),
            ),
        )
        val html = SolrFieldPresentation.fieldTypeDocumentation(spiType, SolrVersionSelection.DEFAULT)
        assertTrue("the tokenizer should link to the tokenizers page", html.contains("tokenizers.html"))
        assertTrue("the filter should link to the filters page", html.contains("filters.html"))
    }

    /** The name stays as the schema wrote it; only the link is resolved. */
    @Test
    fun `an SPI-spelled component is displayed as written`() {
        val spiType = SolrFieldType(
            name = "text_general",
            className = "solr.TextField",
            indexAnalyzer = SolrAnalyzerChain(tokenizer = SolrAnalyzerComponent("standard")),
        )
        val html = SolrFieldPresentation.fieldTypeDocumentation(spiType, SolrVersionSelection.DEFAULT)
        assertTrue("expected the written spelling, got: $html", html.contains("<code>standard</code>"))
        assertFalse(html.contains("StandardTokenizerFactory"))
    }
}
