package org.apache.solr.ide.model.schema

/**
 * A fact about a field type's implementing class that decides what one of its properties defaults to.
 *
 * Generated into the catalog rather than written here, because these enumerate: which of the roughly
 * sixty classes Solr ships descend from which base is exactly the kind of list that grows with Solr
 * and that nobody can keep correct by hand. The arithmetic that turns a trait into a value —
 * `omitNorms` is on for a primitive type only above schema version 1.4 — stays in
 * [SolrTypeDefaultRule], because that is semantics and there are five of them.
 *
 * @property token the word the generated catalog uses for this trait
 */
enum class SolrTypeTrait(internal val token: String) {

    /**
     * Descends from `PrimitiveFieldType`, whose `init` sets `omitNorms` above schema version 1.4.
     *
     * Every numeric, boolean, string, date, UUID and enum type, which is most of a schema.
     */
    PRIMITIVE("primitive"),

    /**
     * Descends from `AbstractSpatialPrefixTreeFieldType`, whose `init` sets `omitNorms` outright.
     *
     * Separate from [PRIMITIVE] because it is not reachable from it — a spatial type descends from
     * `AbstractSpatialFieldType` — and because it carries no version condition.
     */
    SPATIAL_PREFIX_TREE("spatialPrefixTree"),

    /**
     * Descends from `SortableTextField`, whose `init` sets `docValues` outside the version gate.
     *
     * The gate lives in `FieldType.setArgs` and only opens at schema version 1.7; this type sets the
     * bit itself afterwards, so it has doc values on a schema too old for the general rule.
     */
    SORTABLE_TEXT("sortableText"),

    /**
     * `enableDocValuesByDefault` resolves to true for this class.
     *
     * The nearest declaration wins, which is why this is a recorded answer rather than a walk for
     * any ancestor returning true: `DenseVectorField` descends from `PrimitiveFieldType`, which
     * returns true, and overrides it back to false.
     */
    DOC_VALUES_BY_DEFAULT("docValuesByDefault");

    /** Reading the tokens the generated catalog writes. */
    companion object {

        private val BY_TOKEN: Map<String, SolrTypeTrait> = entries.associateBy { it.token }

        /**
         * The trait [token] names, or null when the catalog names one this build does not know.
         *
         * Null rather than an error: a catalog generated by a newer build carrying a trait this one
         * has never heard of should cost that one trait, not the whole entry.
         *
         * @param token a word from the catalog's traits column
         * @return the trait, or null
         */
        fun forToken(token: String): SolrTypeTrait? = BY_TOKEN[token]
    }
}

/**
 * How a property's default is decided once the field type's class is known.
 *
 * One constant per property that has such a rule, holding the rule itself. Written here rather than
 * generated for the reason the schema-version rules are: there are two, the Reference Guide states
 * both in prose, and they are semantics rather than an enumeration.
 */
enum class SolrTypeDefaultRule {

    /**
     * `omitNorms`: on for primitive types above schema version 1.4, and for spatial prefix-tree
     * types at every version.
     */
    OMIT_NORMS {
        override fun holdsFor(traits: Set<SolrTypeTrait>, schemaVersion: SolrSchemaVersion): Boolean =
            SolrTypeTrait.SPATIAL_PREFIX_TREE in traits ||
                (SolrTypeTrait.PRIMITIVE in traits && schemaVersion.declared > 1.4f)
    },

    /**
     * `docValues`: on from schema version 1.7 for types that support it, and at every version for a
     * sortable text type, which sets the bit itself rather than through the gate.
     */
    DOC_VALUES {
        override fun holdsFor(traits: Set<SolrTypeTrait>, schemaVersion: SolrSchemaVersion): Boolean =
            SolrTypeTrait.SORTABLE_TEXT in traits ||
                (SolrTypeTrait.DOC_VALUES_BY_DEFAULT in traits && schemaVersion.declared >= 1.7f)
    };

    /**
     * Whether the property defaults to `true` for a type carrying [traits] on this schema.
     *
     * @param traits the field type's traits, from the catalog
     * @param schemaVersion the schema's declared version
     * @return true when Solr's default for this combination is `true`
     */
    abstract fun holdsFor(traits: Set<SolrTypeTrait>, schemaVersion: SolrSchemaVersion): Boolean
}
